game = {}

function game:load()

  --TODO: Make ground based on map, make rects based on players

  love.physics.setMeter(64) --the height of a meter our worlds will be 64px
  world = love.physics.newWorld(0, 9.81*64, true) --create a world for the bodies to exist in with horizontal gravity of 0 and vertical gravity of 9.81
  love.graphics.setBackgroundColor(0.41, 0.53, 0.97) --set the background color to a nice blue
  love.window.setMode(650, 650) --set the window dimensions to 650 by 650

  objects = {} -- table to hold all our physical objects

  objects.ground = {}
  objects.ground.body = love.physics.newBody(world, 650/2, 650-50/2) --remember, the shape (the rectangle we create next) anchors to the body from its center, so we have to move it to (650/2, 650-50/2)
  objects.ground.shape = love.physics.newRectangleShape(650, 50) --make a rectangle with a width of 650 and a height of 50
  objects.ground.fixture = love.physics.newFixture(objects.ground.body, objects.ground.shape); --attach shape to body

  objects.player = {}
  objects.player.body = love.physics.newBody(world, 200, 550, "dynamic")
  objects.player.shape = love.physics.newRectangleShape(0, 0, 50, 100)
  objects.player.fixture = love.physics.newFixture(objects.player.body, objects.player.shape, 5) -- A higher density gives it more mass.
end

function game:update(dt)
  world:update(dt) --this puts the world into motion

 --here we are going to create some keyboard events
 if love.keyboard.isDown("right") then --press the right arrow key to push the player to the right
   objects.player.body:applyForce(4000, 0)
 elseif love.keyboard.isDown("left") then --press the left arrow key to push the player to the left
   objects.player.body:applyForce(-4000, 0)
 elseif love.keyboard.isDown("up") then --press the up arrow key to set the player in the air
   objects.player.body:applyForce(0, -4000) --we must set the velocity to zero to prevent a potentially large velocity generated by the change in position
 elseif love.keyboard.isDown("space") then --press the up arrow key to set the player in the air
   objects.player.body:setPosition(650/2, 650/2)
   objects.player.body:setLinearVelocity(0, 0) --we must set the velocity to zero to prevent a potentially large velocity generated by the change in position
 end
end

function game:draw()
  love.graphics.setColor(0.28, 0.63, 0.05) -- set the drawing color to green for the ground
  love.graphics.polygon("fill", objects.ground.body:getWorldPoints(objects.ground.shape:getPoints())) -- draw a "filled in" polygon using the ground's coordinates

  love.graphics.setColor(0.76, 0.18, 0.05) --set the drawing color to red for the player
  love.graphics.polygon("fill", objects.player.body:getWorldPoints(objects.player.shape:getPoints()))
end

return game
